system:
  security:
    # 加密用私鑰
    secret: YKOzqnZpV37eAFwPLwWkZdVXwDTOrF7zu7vp8F1VC3g9McUGcJQyjFojv4QiuYoUvQXfahOtL902kI1AJBXGohjwQasOdOzeRQPYxH6kUNU9CMk1n_Mdd_d3_2FY6JcbyF-tCqIqiofckNFfpU6Emye-uiM77GSuSIgwYj2f3l7xymGLKo1Gd8XvEmPCMA9JgSINDI0T7ZUsx5lygYTiQ3KfZSqE-feLOjqpY6PRyLnGV1SF0roMPRPvz8af7dq-KMBk5Pgn0nauK7pwMaoHM5mIfXemltYaRgJ8129iygG8tyZLbbDWMbDVZYcvA8ULsKtVNww7dhwKQFD_2HWv6Q
    # Token到期時間(秒)
    expiration: 3600
    # Refresh Token到期時間(秒)
    refresh-expiration: 1

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/Auth
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update